#!/bin/bash

# apres la creation d'un compte dans https://dashboard.ngrok.com/get-started/setup/linux
# TU RUN this commands

curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok

ngrok config add-authtoken 2ZdbFPs1NJvkU0WO52zxha3acqo_Sa7BjhqzXDmNXSXMZWdm #this token is available just for this account

# deploy 
sudo ngrok http 80
